# Generated by Django 5.0.3 on 2024-05-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tnumbnail",
            field=models.ImageField(
                blank=True, upload_to="post", verbose_name="썸네일 이미지"
            ),
        ),
    ]
