# Generated by Django 5.0.3 on 2024-05-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0002_post_tnumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tnumbnail",
            new_name="thumbnail",
        ),
    ]
